services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: database
    ports:
      - 5432:5432

  server:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
