services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: database
    ports:
      - 5432:5432

  server:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_GRAPHQL_API_URL: "http://localhost:4000"

  servertest:
    build:
      context: ./servertest
      dockerfile: Dockerfile
    container_name: servertest
    ports:
      - 5000:5000
    volumes:
      - ./servertest/src:/app/src
