name: healthchecker-ci

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://host.docker.internal:3000,http://localhost:4000"
          envkey_NODE_ENV: development
          envkey_SERVER_HOST: localhost
          envkey_SERVER_PORT: 4000
          envkey_DATABASE_HOST: database
          envkey_JWT_PRIVATE_KEY: sqdqsdqsdqsdqsdqsd122qs5qsd
          file_name: .env
      - name: install dependency global and server
        run: npm i -g pnpm && pnpm install --no-frozen-lockfile && cd server && pnpm install --no-frozen-lockfile
      - name: exec unit tests
        run: pnpm test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://host.docker.internal:3000,http://localhost:4000"
          envkey_NODE_ENV: development
          envkey_SERVER_HOST: localhost
          envkey_SERVER_PORT: 4000
          envkey_DATABASE_HOST: database
          envkey_JWT_PRIVATE_KEY: sqdqsdqsdqsdqsdqsd122qs5qsd
          directory: server
          file_name: .env
      - name: Run e2e tests
        run: npm i -g pnpm && pnpm install --no-frozen-lockfile && pnpm e2e-tests
  docker:
    needs: [unit-tests, e2e-tests]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/healthchecker:latest
          build-args: |
            "REACT_APP_GRAPHQL_API_URL=${{ vars.REACT_APP_GRAPHQL_API_URL }}"
